// Mobile audio engine using just_audio with generated sample cache
// Samples are generated once at startup based on user settings
// For web, use audio_engine_web.dart

import 'dart:typed_data';
import 'package:flutter/foundation.dart';
import 'package:just_audio/just_audio.dart';
import 'metronome_sample_generator.dart';
import '../../models/metronome_tone_config.dart';

/// Audio engine for metronome with user-configurable tones
/// 
/// **Architecture:**
/// 1. User defines frequencies in settings (tone matrix)
/// 2. Generator creates samples once at startup
/// 3. Samples cached in memory (zero runtime synthesis)
/// 4. Regenerate only when user changes settings
/// 
/// **2-Step System Support:**
/// - Main beat (regular + accent)
/// - Sub beat (regular + accent)
/// - Divider beat (regular + accent)
class AudioEngine {
  /// Sample generator - creates PCM data from settings
  final MetronomeSampleGenerator _generator = MetronomeSampleGenerator();
  
  /// Player pool for overlapping clicks
  final List<AudioPlayer> _players = [];
  static const int _poolSize = 4;
  
  bool _initialized = false;
  int _currentPlayerIndex = 0;

  /// Check if engine is ready
  bool get initialized => _initialized;
  
  /// Get current tone configuration
  MetronomeToneConfig get toneConfig => _generator.config;

  /// Initialize audio engine and generate samples
  /// 
  /// Call this at app startup or when tone settings change
  Future<void> initialize([MetronomeToneConfig? config]) async {
    if (_initialized && config == null) return;

    try {
      // Create player pool if not exists
      if (_players.isEmpty) {
        for (int i = 0; i < _poolSize; i++) {
          final player = AudioPlayer();
          await player.setVolume(1.0);
          await player.setReleaseMode(ReleaseMode.stop);
          _players.add(player);
        }
      }
      
      // Update config if provided
      if (config != null) {
        await _generator.updateConfig(config);
      } else if (!_generator.isInitialized) {
        await _generator.generateAllSamples();
      }
      
      _initialized = true;
      debugPrint('[AudioEngine] Mobile initialized with ${_generator.config.waveType} wave');
    } catch (e) {
      debugPrint('[AudioEngine] Failed: $e');
      rethrow;
    }
  }

  /// Update tone configuration and regenerate samples
  /// 
  /// Call this when user changes frequency settings
  Future<void> updateToneConfig(MetronomeToneConfig config) async {
    await _generator.updateConfig(config);
    debugPrint('[AudioEngine] Tone config updated: ${config.waveType}');
  }

  /// Play click for specific beat type and accent state
  Future<void> playBeat({
    required BeatType beatType,
    required AccentState accent,
  }) async {
    if (!_initialized) await initialize();

    try {
      // Get pre-generated sample
      final bytes = _generator.getSampleOrGenerate(beatType, accent);
      await _playFromBytes(bytes, _generator.config.volume);
      
      // Round-robin player selection
      _currentPlayerIndex = (_currentPlayerIndex + 1) % _poolSize;
    } catch (e) {
      debugPrint('[AudioEngine] Error: $e');
    }
  }

  /// Legacy playClick method (backward compatibility)
  Future<void> playClick({
    required bool isAccent,
    required String waveType,
    required double volume,
    double? accentFrequency,
    double? beatFrequency,
  }) async {
    // Map old API to new 2-step system
    final beatType = isAccent ? BeatType.main : BeatType.sub;
    final accent = isAccent ? AccentState.accent : AccentState.regular;
    await playBeat(beatType: beatType, accent: accent);
  }

  /// Play audio from pre-generated bytes
  Future<void> _playFromBytes(Uint8List bytes, double volume) async {
    if (_players.isEmpty) return;
    
    final player = _players[_currentPlayerIndex];
    
    try {
      await player.stop();
      await player.setVolume(volume.clamp(0.0, 1.0));
      await player.setAudioSource(
        ConcatenatingAudioSource(children: [
          AudioSource.byteData(ByteData.sublistView(bytes)),
        ]),
        preload: false,
      );
      await player.play();
    } catch (e) {
      debugPrint('[AudioEngine] Playback error: $e');
    }
  }

  /// Play test sound using current configuration
  Future<void> playTest() async {
    if (!_initialized) await initialize();
    
    // Play main accent
    await playBeat(beatType: BeatType.main, accent: AccentState.accent);
    await Future.delayed(const Duration(milliseconds: 300));
    
    // Play main regular
    await playBeat(beatType: BeatType.main, accent: AccentState.regular);
    await Future.delayed(const Duration(milliseconds: 300));
    
    // Play sub accent
    await playBeat(beatType: BeatType.sub, accent: AccentState.accent);
    await Future.delayed(const Duration(milliseconds: 300));
    
    // Play sub regular
    await playBeat(beatType: BeatType.sub, accent: AccentState.regular);
    
    debugPrint('[AudioEngine] Test complete');
  }

  /// Get current sample cache info (for debugging)
  Map<String, dynamic> getCacheInfo() {
    return _generator.getCacheInfo();
  }

  /// Dispose resources
  void dispose() {
    for (final player in _players) {
      player.dispose();
    }
    _players.clear();
    _generator.clearCache();
    _initialized = false;
    debugPrint('[AudioEngine] Disposed');
  }
}
